// GENERATED by scripts/build_haem_examples.mjs — do not edit by hand; re-run the script.
// The recurrent translocations of haematological malignancy as example breakend rows. Every
// coordinate is DERIVED from the bundled reference tables by the rules documented in the generator
// (canonical-intron midpoints, J-cluster midpoints, span flanks, 3\u2032UTR midpoints) and every row is
// verified through the classifier before being written here. Not patient data.
//
// For a chimera the expectation record also carries the coding-level facts the generator verified:
// the transcript-order intron on each side, the donor's retained coding bases and residue count, the
// acceptor's coding loss and first retained residue, the protein features that survive whole
// (coordinates from the bundled MANE domain table), and how many coding bases of margin the chosen
// intron has over what those features require. Those are what stop the set drifting into a junction
// that still classifies as a fusion but cuts the domain the fusion is defined by.
//
// An immunoglobulin or T-cell-receptor row carries which part of the locus the derivative really
// ends up with. The break is at the J-segment midpoint; the preferred side is the 3\u2032 end of the
// locus, where the constant genes are. But a normal derivative carries exactly one centromere, and
// in 5 of the 15 rows the gene side and the preferred locus side would both carry one, or
// neither would. Those rows keep the variable-segment side instead: not a preference, the only
// monocentric answer for that geometry, and what really happens in t(4;14), where the two halves of
// the locus land on different derivatives. igSide, igSideForcedByCentromere and the segment counts
// record which it was; all are counted from data/ig-genes.json. This tool holds no enhancer
// coordinates at all, so nothing here says an enhancer is present or absent.
//
// karyotype / coordinateFallsInQuotedBand / bandDifferences: the karyotype is the published
// designation of the disease entity, quoted so a reader can search the literature with it; the bands
// beside it are derived from data/cytobands.json. The chromosomes and the arms always agree on every
// row, and the build fails if they ever do not. On 3 rows the sub-band does not agree, and each
// of those is set out below with the numbers it rests on — the same records are carried on the rows
// themselves as bandDifferences. The bundled tables hold only today's band boundaries, so nothing
// here dates the difference or says which of the two names moved: it says what each of them is.
//   RUNX1::RUNX1T1 — label t(8;21)(q22;q22), coordinates in 21q22.12 and 8q21.3
//     chr8: the karyotype quotes 8q22, which spans 92300000-105100000 in the bundled cytoband table, the
//     next band along q from 8q21. RUNX1T1 lies at 8:91954972-92103385, wholly inside 8q21.3, with 196614
//     bases between it and 8q22, so no breakpoint in RUNX1T1 can fall in the quoted band. The row keeps the
//     published name because that is the string the literature is searched with.
//   BIRC3::MALT1 — label t(11;18)(q21;q21), coordinates in 11q22.2 and 18q21.32
//     chr11: the karyotype quotes 11q21, which spans 93000000-97400000 in the bundled cytoband table, the
//     next band along q from 11q22. BIRC3 lies at 11:102317484-102339403, wholly inside 11q22.2, with
//     4917484 bases between it and 11q21, so no breakpoint in BIRC3 can fall in the quoted band. The row
//     keeps the published name because that is the string the literature is searched with.
//   TRD::TAL1 — label t(1;14)(p32;q11), coordinates in 14q11.2 and 1p33
//     chr1: the karyotype quotes 1p32, which spans 50200000-60800000 in the bundled cytoband table, the
//     next band along p from 1p33. TAL1 lies at 1:47216291-47232225, wholly inside 1p33, with 2967774 bases
//     between it and 1p32, so no breakpoint in TAL1 can fall in the quoted band. The row keeps the
//     published name because that is the string the literature is searched with.

export const FUSION_HAEM_EXAMPLES = [
  '22:23289980N[9:130844794[\t22q11.23;9q34.12\tBND\tBCR::ABL1 — chronic myeloid leukaemia — the Philadelphia chromosome, published karyotype t(9;22)(q34;q11)',
  '12:11877207N]21:34970902]\t12p13.2;21q22.12\tBND\tETV6::RUNX1 — paediatric B-cell acute lymphoblastic leukaemia, published karyotype t(12;21)(p13;q22)',
  '15:74033946N[17:40339856[\t15q24.1;17q21.2\tBND\tPML::RARA — acute promyelocytic leukaemia, published karyotype t(15;17)(q24;q21)',
  '21:34847037]8:92046664]N\t21q22.12;8q21.3\tBND\tRUNX1::RUNX1T1 — acute myeloid leukaemia, published karyotype t(8;21)(q22;q22)',
  '11:118484588N[4:87046490[\t11q23.3;4q21.3\tBND\tKMT2A::AFF1 — infant acute lymphoblastic leukaemia, published karyotype t(4;11)(q21;q23)',
  '5:171392254N]2:29224494]\t5q35.1;2p23.2\tBND\tNPM1::ALK — anaplastic large-cell lymphoma, published karyotype t(2;5)(p23;q35)',
  '19:1617466[1:164677902[N\t19p13.3;1q23.3\tBND\tTCF3::PBX1 — B-cell acute lymphoblastic leukaemia, published karyotype t(1;19)(q23;p13)',
  '12:11861492N]5:150128185]\t12p13.2;5q32\tBND\tETV6::PDGFRB — myeloid neoplasm with eosinophilia, published karyotype t(5;12)(q32;p13)',
  '11:102336490N[18:58715022[\t11q22.2;18q21.32\tBND\tBIRC3::MALT1 — MALT lymphoma, published karyotype t(11;18)(q21;q21)',
  '14:105864327N[8:127735231[\t14q32.33;8q24.21\tBND\tIGH::MYC — Burkitt lymphoma, published karyotype t(8;14)(q24;q32)',
  '8:127743951N]2:88861245]\t8q24.21;2p11.2\tBND\tIGK::MYC — Burkitt lymphoma variant, published karyotype t(2;8)(p11;q24)',
  '8:127743951N[22:22907608[\t8q24.21;22q11.22\tBND\tIGL::MYC — Burkitt lymphoma variant, published karyotype t(8;22)(q24;q11)',
  '14:105864327N[18:63125985[\t14q32.33;18q21.33\tBND\tIGH::BCL2 — follicular lymphoma, published karyotype t(14;18)(q32;q21)',
  '14:105864327]3:187746468]N\t14q32.33;3q27.3\tBND\tIGH::BCL6 — diffuse large B-cell lymphoma, published karyotype t(3;14)(q27;q32)',
  '14:105864327N[11:69640156[\t14q32.33;11q13.3\tBND\tIGH::CCND1 — mantle cell lymphoma, published karyotype t(11;14)(q13;q32)',
  '14:105864327N]6:41942808]\t14q32.33;6p21.1\tBND\tIGH::CCND3 — plasma cell myeloma, published karyotype t(6;14)(p21;q32)',
  '14:105864327[4:1870393[N\t14q32.33;4p16.3\tBND\tIGH::NSD2 — plasma cell myeloma, published karyotype t(4;14)(p16;q32)',
  '16:79592838]14:105864327]N\t16q23.2;14q32.33\tBND\tIGH::MAF — plasma cell myeloma, published karyotype t(14;16)(q32;q23)',
  '20:40684848]14:105864327]N\t20q12;14q32.33\tBND\tIGH::MAFB — plasma cell myeloma, published karyotype t(14;20)(q32;q12)',
  '14:105864327N[19:44747708[\t14q32.33;19q13.32\tBND\tIGH::BCL3 — chronic lymphocytic leukaemia, published karyotype t(14;19)(q32;q13)',
  '14:105864327N[18:58670465[\t14q32.33;18q21.32\tBND\tIGH::MALT1 — MALT lymphoma, published karyotype t(14;18)(q32;q21)',
  '14:22454622N]1:47233225]\t14q11.2;1p33\tBND\tTRD::TAL1 — T-cell acute lymphoblastic leukaemia, published karyotype t(1;14)(p32;q11)',
  '14:22454622N[10:101130300[\t14q11.2;10q24.31\tBND\tTRD::TLX1 — T-cell acute lymphoblastic leukaemia, published karyotype t(10;14)(q24;q11)',
  '14:22454622N]11:33893076]\t14q11.2;11p13\tBND\tTRD::LMO2 — T-cell acute lymphoblastic leukaemia, published karyotype t(11;14)(p13;q11)'
].join('\n');

/** What each example must classify as — asserted by fusion.test.mjs so the set cannot drift. */
export const FUSION_HAEM_EXPECTATIONS = [
  {
    "name": "BCR::ABL1",
    "disease": "chronic myeloid leukaemia — the Philadelphia chromosome, published karyotype t(9;22)(q34;q11)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "BCR",
      "ABL1"
    ],
    "der": "der(22)",
    "donorIntron": 13,
    "acceptorIntron": 1,
    "donorCodingBases": 2707,
    "donorResiduesRetained": 902,
    "acceptorCodingLost": 79,
    "acceptorFirstResidue": 27,
    "donorBasesRequired": 165,
    "donorMarginBases": 2542,
    "acceptorLossAllowed": 180,
    "acceptorMarginBases": 101,
    "keepsWhole": [
      {
        "gene": "BCR",
        "feature": "Coiled coil",
        "start": 28,
        "end": 55
      },
      {
        "gene": "ABL1",
        "feature": "SH3",
        "start": 61,
        "end": 121
      },
      {
        "gene": "ABL1",
        "feature": "SH2",
        "start": 127,
        "end": 217
      },
      {
        "gene": "ABL1",
        "feature": "Protein kinase",
        "start": 242,
        "end": 493
      }
    ],
    "karyotype": "t(9;22)(q34;q11)",
    "bands": [
      "22q11.23",
      "9q34.12"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "ETV6::RUNX1",
    "disease": "paediatric B-cell acute lymphoblastic leukaemia, published karyotype t(12;21)(p13;q22)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "ETV6",
      "RUNX1"
    ],
    "der": "der(21)",
    "donorIntron": 5,
    "acceptorIntron": 2,
    "donorCodingBases": 1009,
    "donorResiduesRetained": 336,
    "acceptorCodingLost": 58,
    "acceptorFirstResidue": 20,
    "donorBasesRequired": 372,
    "donorMarginBases": 637,
    "acceptorLossAllowed": 228,
    "acceptorMarginBases": 170,
    "keepsWhole": [
      {
        "gene": "ETV6",
        "feature": "PNT",
        "start": 40,
        "end": 124
      },
      {
        "gene": "RUNX1",
        "feature": "Runt",
        "start": 77,
        "end": 205
      },
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 107,
        "end": 111
      },
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 162,
        "end": 170
      },
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 195,
        "end": 204
      }
    ],
    "karyotype": "t(12;21)(p13;q22)",
    "bands": [
      "12p13.2",
      "21q22.12"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "PML::RARA",
    "disease": "acute promyelocytic leukaemia, published karyotype t(15;17)(q24;q21)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "PML",
      "RARA"
    ],
    "der": "der(15)",
    "donorIntron": 6,
    "acceptorIntron": 2,
    "donorCodingBases": 1657,
    "donorResiduesRetained": 552,
    "acceptorCodingLost": 178,
    "acceptorFirstResidue": 60,
    "donorBasesRequired": 708,
    "donorMarginBases": 949,
    "acceptorLossAllowed": 261,
    "acceptorMarginBases": 83,
    "keepsWhole": [
      {
        "gene": "PML",
        "feature": "RING-type",
        "start": 57,
        "end": 92
      },
      {
        "gene": "PML",
        "feature": "B box-type 2",
        "start": 183,
        "end": 236
      },
      {
        "gene": "RARA",
        "feature": "Nuclear receptor",
        "start": 88,
        "end": 153
      },
      {
        "gene": "RARA",
        "feature": "NR LBD",
        "start": 183,
        "end": 417
      }
    ],
    "karyotype": "t(15;17)(q24;q21)",
    "bands": [
      "15q24.1",
      "17q21.2"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "RUNX1::RUNX1T1",
    "disease": "acute myeloid leukaemia, published karyotype t(8;21)(q22;q22)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "RUNX1",
      "RUNX1T1"
    ],
    "der": "der(8)",
    "donorIntron": 6,
    "acceptorIntron": 2,
    "donorCodingBases": 613,
    "donorResiduesRetained": 204,
    "acceptorCodingLost": 88,
    "acceptorFirstResidue": 30,
    "donorBasesRequired": 612,
    "donorMarginBases": 1,
    "acceptorLossAllowed": 357,
    "acceptorMarginBases": 269,
    "keepsWhole": [
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 107,
        "end": 111
      },
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 162,
        "end": 170
      },
      {
        "gene": "RUNX1",
        "feature": "Interaction with DNA",
        "start": 195,
        "end": 204
      },
      {
        "gene": "RUNX1T1",
        "feature": "TAFH",
        "start": 120,
        "end": 215
      },
      {
        "gene": "RUNX1T1",
        "feature": "Nervy homology region 2 (NHR2)",
        "start": 337,
        "end": 383
      },
      {
        "gene": "RUNX1T1",
        "feature": "Nervy homology region 3 (NHR3)",
        "start": 443,
        "end": 492
      },
      {
        "gene": "RUNX1T1",
        "feature": "MYND-type",
        "start": 515,
        "end": 551
      }
    ],
    "karyotype": "t(8;21)(q22;q22)",
    "bands": [
      "21q22.12",
      "8q21.3"
    ],
    "coordinateFallsInQuotedBand": false,
    "bandDifferences": [
      {
        "chromosome": "8",
        "position": 92046664,
        "band": "8q21.3",
        "karyotypeBand": "8q22",
        "karyotypeBandSpan": [
          92300000,
          105100000
        ],
        "gene": "RUNX1T1",
        "geneSpan": [
          91954972,
          92103385
        ],
        "geneBands": [
          "8q21.3"
        ],
        "basesBetween": 196614,
        "aDifferentCoordinateCouldAgree": false,
        "note": "the karyotype quotes 8q22, which spans 92300000-105100000 in the bundled cytoband table, the next band along q from 8q21. RUNX1T1 lies at 8:91954972-92103385, wholly inside 8q21.3, with 196614 bases between it and 8q22, so no breakpoint in RUNX1T1 can fall in the quoted band. The row keeps the published name because that is the string the literature is searched with."
      }
    ]
  },
  {
    "name": "KMT2A::AFF1",
    "disease": "infant acute lymphoblastic leukaemia, published karyotype t(4;11)(q21;q23)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "KMT2A",
      "AFF1"
    ],
    "der": "der(11)",
    "donorIntron": 9,
    "acceptorIntron": 3,
    "donorCodingBases": 4218,
    "donorResiduesRetained": 1406,
    "acceptorCodingLost": 159,
    "acceptorFirstResidue": 54,
    "donorBasesRequired": 3585,
    "donorMarginBases": 633,
    "acceptorLossAllowed": null,
    "acceptorMarginBases": null,
    "keepsWhole": [
      {
        "gene": "KMT2A",
        "feature": "A.T hook 1",
        "start": 169,
        "end": 180
      },
      {
        "gene": "KMT2A",
        "feature": "A.T hook 2",
        "start": 217,
        "end": 227
      },
      {
        "gene": "KMT2A",
        "feature": "A.T hook 3",
        "start": 301,
        "end": 309
      },
      {
        "gene": "KMT2A",
        "feature": "CXXC-type",
        "start": 1147,
        "end": 1195
      }
    ],
    "karyotype": "t(4;11)(q21;q23)",
    "bands": [
      "11q23.3",
      "4q21.3"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "NPM1::ALK",
    "disease": "anaplastic large-cell lymphoma, published karyotype t(2;5)(p23;q35)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "NPM1",
      "ALK"
    ],
    "der": "der(5)",
    "donorIntron": 4,
    "acceptorIntron": 19,
    "donorCodingBases": 352,
    "donorResiduesRetained": 117,
    "acceptorCodingLost": 3172,
    "acceptorFirstResidue": 1058,
    "donorBasesRequired": null,
    "donorMarginBases": null,
    "acceptorLossAllowed": 3345,
    "acceptorMarginBases": 173,
    "keepsWhole": [
      {
        "gene": "ALK",
        "feature": "Protein kinase",
        "start": 1116,
        "end": 1392
      }
    ],
    "karyotype": "t(2;5)(p23;q35)",
    "bands": [
      "5q35.1",
      "2p23.2"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "TCF3::PBX1",
    "disease": "B-cell acute lymphoblastic leukaemia, published karyotype t(1;19)(q23;p13)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "TCF3",
      "PBX1"
    ],
    "der": "der(19)",
    "donorIntron": 16,
    "acceptorIntron": 2,
    "donorCodingBases": 1450,
    "donorResiduesRetained": 483,
    "acceptorCodingLost": 265,
    "acceptorFirstResidue": 89,
    "donorBasesRequired": 81,
    "donorMarginBases": 1369,
    "acceptorLossAllowed": 696,
    "acceptorMarginBases": 431,
    "keepsWhole": [
      {
        "gene": "TCF3",
        "feature": "9aaTAD",
        "start": 19,
        "end": 27
      },
      {
        "gene": "PBX1",
        "feature": "Homeobox; TALE-type",
        "start": 233,
        "end": 295
      }
    ],
    "karyotype": "t(1;19)(q23;p13)",
    "bands": [
      "19p13.3",
      "1q23.3"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "ETV6::PDGFRB",
    "disease": "myeloid neoplasm with eosinophilia, published karyotype t(5;12)(q32;p13)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "ETV6",
      "PDGFRB"
    ],
    "der": "der(5)",
    "donorIntron": 4,
    "acceptorIntron": 10,
    "donorCodingBases": 463,
    "donorResiduesRetained": 154,
    "acceptorCodingLost": 1579,
    "acceptorFirstResidue": 527,
    "donorBasesRequired": 372,
    "donorMarginBases": 91,
    "acceptorLossAllowed": 1797,
    "acceptorMarginBases": 218,
    "keepsWhole": [
      {
        "gene": "ETV6",
        "feature": "PNT",
        "start": 40,
        "end": 124
      },
      {
        "gene": "PDGFRB",
        "feature": "Protein kinase",
        "start": 600,
        "end": 962
      }
    ],
    "karyotype": "t(5;12)(q32;p13)",
    "bands": [
      "12p13.2",
      "5q32"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "BIRC3::MALT1",
    "disease": "MALT lymphoma, published karyotype t(11;18)(q21;q21)",
    "kind": "chimeric-candidate",
    "inFrame": true,
    "reads": [
      "BIRC3",
      "MALT1"
    ],
    "der": "der(11)",
    "donorIntron": 7,
    "acceptorIntron": 8,
    "donorCodingBases": 1579,
    "donorResiduesRetained": 526,
    "acceptorCodingLost": 985,
    "acceptorFirstResidue": 329,
    "donorBasesRequired": 966,
    "donorMarginBases": 613,
    "acceptorLossAllowed": 1041,
    "acceptorMarginBases": 56,
    "keepsWhole": [
      {
        "gene": "BIRC3",
        "feature": "BIR 1",
        "start": 29,
        "end": 96
      },
      {
        "gene": "BIRC3",
        "feature": "BIR 2",
        "start": 169,
        "end": 235
      },
      {
        "gene": "BIRC3",
        "feature": "BIR 3",
        "start": 255,
        "end": 322
      },
      {
        "gene": "MALT1",
        "feature": "Caspase-like",
        "start": 348,
        "end": 562
      }
    ],
    "karyotype": "t(11;18)(q21;q21)",
    "bands": [
      "11q22.2",
      "18q21.32"
    ],
    "coordinateFallsInQuotedBand": false,
    "bandDifferences": [
      {
        "chromosome": "11",
        "position": 102336490,
        "band": "11q22.2",
        "karyotypeBand": "11q21",
        "karyotypeBandSpan": [
          93000000,
          97400000
        ],
        "gene": "BIRC3",
        "geneSpan": [
          102317484,
          102339403
        ],
        "geneBands": [
          "11q22.2"
        ],
        "basesBetween": 4917484,
        "aDifferentCoordinateCouldAgree": false,
        "note": "the karyotype quotes 11q21, which spans 93000000-97400000 in the bundled cytoband table, the next band along q from 11q22. BIRC3 lies at 11:102317484-102339403, wholly inside 11q22.2, with 4917484 bases between it and 11q21, so no breakpoint in BIRC3 can fall in the quoted band. The row keeps the published name because that is the string the literature is searched with."
      }
    ]
  },
  {
    "name": "IGH::MYC",
    "disease": "Burkitt lymphoma, published karyotype t(8;14)(q24;q32)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "MYC",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(8;14)(q24;q32)",
    "bands": [
      "14q32.33",
      "8q24.21"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGK::MYC",
    "disease": "Burkitt lymphoma variant, published karyotype t(2;8)(p11;q24)",
    "kind": "enhancer-adoption",
    "locus": "IGK",
    "target": "MYC",
    "der": "der(8)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 1,
    "igConstantGenesInLocus": 1,
    "igJoiningSegmentsKept": 2,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(2;8)(p11;q24)",
    "bands": [
      "8q24.21",
      "2p11.2"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGL::MYC",
    "disease": "Burkitt lymphoma variant, published karyotype t(8;22)(q24;q11)",
    "kind": "enhancer-adoption",
    "locus": "IGL",
    "target": "MYC",
    "der": "der(8)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 1,
    "igConstantGenesInLocus": 4,
    "igJoiningSegmentsKept": 4,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(8;22)(q24;q11)",
    "bands": [
      "8q24.21",
      "22q11.22"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::BCL2",
    "disease": "follicular lymphoma, published karyotype t(14;18)(q32;q21)",
    "kind": "deregulation-candidate",
    "locus": "IGH",
    "target": "BCL2",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(14;18)(q32;q21)",
    "bands": [
      "14q32.33",
      "18q21.33"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::BCL6",
    "disease": "diffuse large B-cell lymphoma, published karyotype t(3;14)(q27;q32)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "BCL6",
    "der": "der(3)",
    "igSide": "variable-segment",
    "igSideForcedByCentromere": true,
    "igConstantGenesKept": 0,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 27,
    "igVariableSegmentsKept": 48,
    "karyotype": "t(3;14)(q27;q32)",
    "bands": [
      "14q32.33",
      "3q27.3"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::CCND1",
    "disease": "mantle cell lymphoma, published karyotype t(11;14)(q13;q32)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "CCND1",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(11;14)(q13;q32)",
    "bands": [
      "14q32.33",
      "11q13.3"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::CCND3",
    "disease": "plasma cell myeloma, published karyotype t(6;14)(p21;q32)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "CCND3",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(6;14)(p21;q32)",
    "bands": [
      "14q32.33",
      "6p21.1"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::NSD2",
    "disease": "plasma cell myeloma, published karyotype t(4;14)(p16;q32)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "NSD2",
    "der": "der(4)",
    "igSide": "variable-segment",
    "igSideForcedByCentromere": true,
    "igConstantGenesKept": 0,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 27,
    "igVariableSegmentsKept": 48,
    "karyotype": "t(4;14)(p16;q32)",
    "bands": [
      "14q32.33",
      "4p16.3"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::MAF",
    "disease": "plasma cell myeloma, published karyotype t(14;16)(q32;q23)",
    "kind": "enhancer-adoption",
    "locus": "IGH",
    "target": "MAF",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(14;16)(q32;q23)",
    "bands": [
      "16q23.2",
      "14q32.33"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::MAFB",
    "disease": "plasma cell myeloma, published karyotype t(14;20)(q32;q12)",
    "kind": "enhancer-adoption",
    "locus": "IGH",
    "target": "MAFB",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(14;20)(q32;q12)",
    "bands": [
      "20q12",
      "14q32.33"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::BCL3",
    "disease": "chronic lymphocytic leukaemia, published karyotype t(14;19)(q32;q13)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "BCL3",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(14;19)(q32;q13)",
    "bands": [
      "14q32.33",
      "19q13.32"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "IGH::MALT1",
    "disease": "MALT lymphoma, published karyotype t(14;18)(q32;q21)",
    "kind": "unnamed-donor-intact",
    "locus": "IGH",
    "target": "MALT1",
    "der": "der(14)",
    "igSide": "constant-gene",
    "igSideForcedByCentromere": false,
    "igConstantGenesKept": 9,
    "igConstantGenesInLocus": 9,
    "igJoiningSegmentsKept": 3,
    "igDiversitySegmentsKept": 0,
    "igVariableSegmentsKept": 0,
    "karyotype": "t(14;18)(q32;q21)",
    "bands": [
      "14q32.33",
      "18q21.32"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "TRD::TAL1",
    "disease": "T-cell acute lymphoblastic leukaemia, published karyotype t(1;14)(p32;q11)",
    "kind": "unnamed-donor-intact",
    "locus": "TRD",
    "target": "TAL1",
    "der": "der(14)",
    "igSide": "variable-segment",
    "igSideForcedByCentromere": true,
    "igConstantGenesKept": 0,
    "igConstantGenesInLocus": 1,
    "igJoiningSegmentsKept": 1,
    "igDiversitySegmentsKept": 3,
    "igVariableSegmentsKept": 2,
    "karyotype": "t(1;14)(p32;q11)",
    "bands": [
      "14q11.2",
      "1p33"
    ],
    "coordinateFallsInQuotedBand": false,
    "bandDifferences": [
      {
        "chromosome": "1",
        "position": 47233225,
        "band": "1p33",
        "karyotypeBand": "1p32",
        "karyotypeBandSpan": [
          50200000,
          60800000
        ],
        "gene": "TAL1",
        "geneSpan": [
          47216291,
          47232225
        ],
        "geneBands": [
          "1p33"
        ],
        "basesBetween": 2967774,
        "aDifferentCoordinateCouldAgree": false,
        "note": "the karyotype quotes 1p32, which spans 50200000-60800000 in the bundled cytoband table, the next band along p from 1p33. TAL1 lies at 1:47216291-47232225, wholly inside 1p33, with 2967774 bases between it and 1p32, so no breakpoint in TAL1 can fall in the quoted band. The row keeps the published name because that is the string the literature is searched with."
      }
    ]
  },
  {
    "name": "TRD::TLX1",
    "disease": "T-cell acute lymphoblastic leukaemia, published karyotype t(10;14)(q24;q11)",
    "kind": "unnamed-donor-intact",
    "locus": "TRD",
    "target": "TLX1",
    "der": "der(14)",
    "igSide": "variable-segment",
    "igSideForcedByCentromere": true,
    "igConstantGenesKept": 0,
    "igConstantGenesInLocus": 1,
    "igJoiningSegmentsKept": 1,
    "igDiversitySegmentsKept": 3,
    "igVariableSegmentsKept": 2,
    "karyotype": "t(10;14)(q24;q11)",
    "bands": [
      "14q11.2",
      "10q24.31"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  },
  {
    "name": "TRD::LMO2",
    "disease": "T-cell acute lymphoblastic leukaemia, published karyotype t(11;14)(p13;q11)",
    "kind": "unnamed-donor-intact",
    "locus": "TRD",
    "target": "LMO2",
    "der": "der(14)",
    "igSide": "variable-segment",
    "igSideForcedByCentromere": true,
    "igConstantGenesKept": 0,
    "igConstantGenesInLocus": 1,
    "igJoiningSegmentsKept": 1,
    "igDiversitySegmentsKept": 3,
    "igVariableSegmentsKept": 2,
    "karyotype": "t(11;14)(p13;q11)",
    "bands": [
      "14q11.2",
      "11p13"
    ],
    "coordinateFallsInQuotedBand": true,
    "bandDifferences": []
  }
];
